
services:
  kafka-1:
    image: ${KAFKA_IMAGE}
    hostname: kafka-1
    container_name: kafka-kraft-1
    ports:
      - "19092:9092"
    environment:
      KAFKA_NODE_ID: 1
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093,INTERNAL://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092,INTERNAL://kafka-1:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_MESSAGE_MAX_BYTES: 52428800
      KAFKA_REPLICA_FETCH_MAX_BYTES: 52428800
      KAFKA_MAX_REQUEST_SIZE: 52428800
      KAFKA_MAX_PARTITION_FETCH_BYTES: 52428800
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-1:/var/lib/kafka/data
      - kafka-data-1:/var/lib/kafka/data

  kafka-2:
    image: ${KAFKA_IMAGE}
    hostname: kafka-2
    container_name: kafka-kraft-2
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 2
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,CONTROLLER://kafka-2:9093,INTERNAL://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,INTERNAL://kafka-2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-2:/var/lib/kafka/data
      - kafka-data-2:/var/lib/kafka/data

  kafka-3:
    image: ${KAFKA_IMAGE}
    hostname: kafka-3
    container_name: kafka-kraft-3
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 3
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,CONTROLLER://kafka-3:9093,INTERNAL://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092,INTERNAL://kafka-3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-3:/var/lib/kafka/data
      - kafka-data-3:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "kraft-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9094,kafka-2:9094,kafka-3:9094
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      - kafka-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      # - ./container-data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kafka-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./container-conf/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - kafka-net

  hive-metastore-init:
    image: apache/hive:4.0.0
    container_name: hive-metastore-init
    depends_on:
      - postgres
    networks:
      - kafka-net
    volumes:
      - ./container-conf/hive/lib/postgresql-42.7.8.jar:/opt/hive/lib/postgresql-42.7.8.jar
      - ./container-conf/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    entrypoint: >
      bash -c "
        echo 'Waiting for PostgreSQL...';
        echo 'Initializing Hive Metastore schema...';
        while ! </dev/tcp/postgres/5432 >/dev/null 2>&1; do
          echo 'PostgreSQL not ready, retrying...';
          sleep 2;
        done
        schematool -dbType postgres -initSchema --verbose || true;
        echo 'Init completed.';
      "

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      - hive-metastore-init
    # environment:
    #   HIVE_METASTORE_DB_TYPE: postgres
    #   HIVE_METASTORE_DB_HOST: postgres
    #   HIVE_METASTORE_DB_NAME: metastore
    #   HIVE_METASTORE_DB_USER: hive
    #   HIVE_METASTORE_DB_PASS: hivepassword
    entrypoint: >
      bash -c "
        echo 'Waiting for schema initialization...';
        until schematool -dbType postgres -info >/dev/null 2>&1; do
          echo '  Schema not ready... waiting';
          sleep 3;
        done;
        echo 'Schema ready. Starting metastore service...';
        /opt/hive/bin/hive --service metastore
      "
    ports:
      - "9083:9083"
    volumes:
      - ./container-conf/hive/lib/postgresql-42.7.8.jar:/opt/hive/lib/postgresql-42.7.8.jar
      - ./container-conf/hive/conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    networks:
      - kafka-net

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /mnt/data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "/mnt/data"
    volumes:
      # - ./container-data/minio/data:/mnt/data
      - minio-data:/mnt/data
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # - ./container-data/grafana/data:/var/lib/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:
  minio-data:
  postgres-data:
  grafana-data:
