
services:

  # ==========================================================
  #  KAFKA CLUSTER (3 nodes - 1 controller and 2 brokers - Streaming data ingestion layer)
  # ==========================================================
  kafka-1:
    image: ${KAFKA_IMAGE}
    hostname: kafka-1
    container_name: kafka-kraft-1
    ports:
      - "19092:9092"
    environment:
      KAFKA_NODE_ID: 1
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092,CONTROLLER://kafka-1:9093,INTERNAL://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092,INTERNAL://kafka-1:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_MESSAGE_MAX_BYTES: 52428800
      KAFKA_REPLICA_FETCH_MAX_BYTES: 52428800
      KAFKA_MAX_REQUEST_SIZE: 52428800
      KAFKA_MAX_PARTITION_FETCH_BYTES: 52428800
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka-1:9094",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-1:/var/lib/kafka/data
      - kafka-data-1:/var/lib/kafka/data

  kafka-2:
    image: ${KAFKA_IMAGE}
    hostname: kafka-2
    container_name: kafka-kraft-2
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 2
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9092,CONTROLLER://kafka-2:9093,INTERNAL://kafka-2:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,INTERNAL://kafka-2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka-2:9094",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-2:/var/lib/kafka/data
      - kafka-data-2:/var/lib/kafka/data

  kafka-3:
    image: ${KAFKA_IMAGE}
    hostname: kafka-3
    container_name: kafka-kraft-3
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 3
    #   KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9092,CONTROLLER://kafka-3:9093,INTERNAL://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092,INTERNAL://kafka-3:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_DIR: /var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "./opt/kafka/bin/kafka-topics.sh --list --bootstrap-server kafka-3:9094",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      # - ./container-data/kafka/kafka-data-3:/var/lib/kafka/data
      - kafka-data-3:/var/lib/kafka/data

  # ==========================================================
  #  KAFKA UI (Kafka management interface)
  # ==========================================================
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "kraft-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9094,kafka-2:9094,kafka-3:9094
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    networks:
      - kafka-net

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    ports:
      # inside container: 8081, on your host: 8082
      - "8082:8081"
    environment:
      # How Schema Registry identifies itself
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      # Where it listens for HTTP
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

      # How it talks to Kafka (use INTERNAL listener ports, since this is inside Docker)
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: >
        PLAINTEXT://kafka-1:9094,
        PLAINTEXT://kafka-2:9094,
        PLAINTEXT://kafka-3:9094

      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - kafka-net


  # ==========================================================
  #  ADDITIONAL DATABASES
  # ==========================================================
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      # - ./container-data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kafka-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./container-conf/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - kafka-net


  # ==========================================================
  #  TRINO SQL ENGINE
  # ==========================================================
  trino:
    image: trinodb/trino:478
    container_name: trino
    depends_on:
      polaris:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8081:8080"
    volumes:
      - ./container-conf/trino/catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties
    networks:
      - kafka-net
    restart: on-failure:5


  # ==========================================================
  #  MINIO OBJECT STORAGE (Data lake storage layer)
  # ==========================================================
  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /mnt/data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: "/mnt/data"
    volumes:
      # - ./container-data/minio/data:/mnt/data
      - minio-data:/mnt/data
    networks:
      - kafka-net    
    healthcheck:
      test: ["CMD", "curl", "http://127.0.0.1:9000/minio/health/live"]
      interval: 1s
      timeout: 10s

  setup_bucket:
    image: quay.io/minio/mc:latest
    container_name: setup_bucket
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: "/bin/sh"
    command:
      - "-c"
      - >-
        echo Creating MinIO bucket...;
        mc alias set admin http://minio:9000 minioadmin minioadmin;
        mc mb admin/warehouse;
        mc ls admin;
        echo Bucket setup complete.;
    networks:
      - kafka-net

  # ==========================================================
  #  GRAFANA MONITORING DASHBOARD
  # ==========================================================
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # - ./container-data/grafana/data:/var/lib/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - kafka-net

  # ==========================================================
  #  POLARIS - REST DATA CATALOG FOR ICECBERG
  # ==========================================================
  polaris:
    image: apache/polaris:1.2.0-incubating
    container_name: polaris
    ports:
      # API port
      - "8181:8181"
      # Optional, allows attaching a debugger to the Polaris JVM
      - "5005:5005"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_ENDPOINT_URL_S3: http://minio:9000
      AWS_ENDPOINT_URL_STS: http://minio:9000
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,root,s3cr3t
      polaris.features.DROP_WITH_PURGE_ENABLED: true
      polaris.realm-context.realms: POLARIS
      quarkus.otel.sdk.disabled: "true"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/q/health"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - kafka-net

  polaris-setup:
    image: alpine/curl
    container_name: polaris-setup
    depends_on:
      polaris:
        condition: service_healthy
    environment:
      - CLIENT_ID=root
      - CLIENT_SECRET=s3cr3t
    volumes:
      - ./container-conf/polaris/:/polaris
    entrypoint: "/bin/sh"
    command:
      - "-c"
      - >-
        chmod +x /polaris/create-catalog.sh;
        chmod +x /polaris/obtain-token.sh;
        source /polaris/obtain-token.sh;
        echo Creating catalog...;
        export STORAGE_CONFIG_INFO='{"storageType":"S3",
          "endpoint":"http://localhost:9000",
          "endpointInternal":"http://minio:9000",
          "pathStyleAccess":true}';
        export STORAGE_LOCATION='s3://warehouse';
        /polaris/create-catalog.sh POLARIS $$TOKEN;
        echo Extra grants...;
        curl -H "Authorization: Bearer $$TOKEN" -H 'Content-Type: application/json' \
          -X PUT \
          http://polaris:8181/api/management/v1/catalogs/warehouse/catalog-roles/catalog_admin/grants \
          -d '{"type":"catalog", "privilege":"CATALOG_MANAGE_CONTENT"}';
        echo Done.;
    networks:
      - kafka-net

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:
  minio-data:
  postgres-data:
  grafana-data:
